# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: snail-language
author: 
  name: Maintained by Kevin Angstadt
  bio: >-
    Snail (Strings Numbers Arrays and Inheritance Language) is a dynamically typed,
    expression-based, object-oriented programming language that is simple enough
    to be implemented in a one-semester course.
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/snail-language"
email: kangstadt@stlawu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Snail (Strings Numbers Arrays and Inheritance Language) is a dynamically typed,
  expression-based, object-oriented programming language that is simple enough
  to be implemented in a one-semester course.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://snail-language.github.io" # the base hostname & protocol for your site
domain: snail-language.github.io
github_username:  snail-language

highlighter: rouge

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# theme settings
after_footer_scripts: 
  - assets/js/mathjax.js

include: ["_pages", "_docs"]

collections:
  docs:
    output: true
    permalink: /:collection/:path/

atom_feed:
  hide: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/snail-language"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-PE9V5NKJB0"

google_site_verification: "WxeulDVzXQLzte0EgHgp0kj5r31YxC"